services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: shorten
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  app:
    image: shorten:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/shorten
      SPRING_REDIS_HOST: localhost
      SPRING_REDIS_PORT: 6379