services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: shorten

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: false

  app:
    image: shorten:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/shorten
