spring:
  application:
    name: Shorten
  cache:
    redis:
      cache-null-values: false
      time-to-live: 3600s
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: true
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000ms
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:v1.0}
logging:
  level:
    web: debug